title: Stephanie Hoglund # your name (or website title) here
logo: "/images/profile_picture.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of data analytics experience in the automotive and defense industries.
  <br><br>
  Go Blue! 
  <br><br>
  <a href="https://www.linkedin.com/in/stephaniechoglund">View My LinkedIn Profile</a> 
  <a href="https://github.com/schoglund">View My Github</a>
  
theme: jekyll-theme-minimal
google_analytics: G-EQJMQS0LD3 # your Google Analytics tracking ID here
