title: Stephanie Hoglund # your name (or website title) here
logo: "/images/IMG_4794.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  3+ years of experience in data analytics for the defense and automotive industries.
  <br><br>
  Go Blue! 
  <br><br>
  <a href="https://www.linkedin.com/in/stephaniechoglund">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
